MvcManagerCloud/ManagerCloud.MVC/Models/Entities/Item.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ManagerCloud.MVC.Models.Entities
{
    public class Item
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Required to fill")]
        [Display(Name = "Name")]
        [StringLength(255, ErrorMessage = "Too many chars")]
        public string Name { get; set; }
    }
}

MvcManagerCloud/ManagerCloud.MVC/Controllers/ItemsController.cs
using System;
using Newtonsoft.Json;
using System.Linq;
using System.Web.Mvc;
using ManagerCloud.BL;
using ManagerCloud.MVC.Filters;
using ManagerCloud.MVC.Models.Entities;

namespace ManagerCloud.MVC.Controllers
{
    public class ItemsController : Controller
    {
        private readonly Unity _unity = new Unity();

        // GET: Items
        public ActionResult Index()
        {
            return View(Helpers.BlModelConversion.GetListItems());
        }

        public ActionResult AutocompleteSearch(string term)
        {
            var items = Helpers.BlModelConversion.GetListItems()
                .Where(a => a.Name.Contains(term))
                .Select(a => new { value = a.Name })
                .Distinct();

            return Json(items, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(int id)
        {
            var item = Helpers.BlModelConversion.GetListItems().FirstOrDefault(i => i.Id == id);
            if (item != null)
                return PartialView(item);
            return HttpNotFound();
        }

        public string GetData()
        {
            return JsonConvert.SerializeObject(Helpers.BlModelConversion.GetListItems());
        }

        [LocalAuthorize(Roles = "admin")]
        [HttpGet]
        [OutputCache(Duration = 300)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var item = _unity.GetItem((int)id);
            if (item == null)
            {
                return HttpNotFound();
            }

            var customer = new Item
            {
                Id = item.Item1,
                Name = item.Item2
            };

            return View(customer);
        }

        [LocalAuthorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(Item item)
        {
            if (ModelState.IsValid)
            {
                _unity.UpdateItem(new Tuple<int, string>(item.Id, item.Name));
            }
            else
            {
                ViewBag.Message = "Failed";
            }

            ViewBag.Message = "Successful";
            return RedirectToAction("Index");
        }

        [LocalAuthorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [LocalAuthorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(Item item)
        {
            if (ModelState.IsValid)
            {
                _unity.AddItem(item.Name);
            }
            else
            {
                ViewBag.Message = "Failed";
            }

            ViewBag.Message = "Successful";
            return RedirectToAction("Index");
        }

        [LocalAuthorize(Roles = "admin")]
        [OutputCache(Duration = 300)]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var item = _unity.GetItem((int)id);
            if (item == null)
            {
                return HttpNotFound();
            }

            var customer = new Item
            {
                Id = item.Item1,
                Name = item.Item2
            };

            return View(customer);
        }

        [LocalAuthorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var client = _unity.GetItem(id);
            if (client == null)
            {
                return RedirectToAction("Index");
            }

            _unity.RemoveItem(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult ItemSearch(string iName)
        {
            var client = Helpers.BlModelConversion.GetListItems().FirstOrDefault(x => x.Name == iName);

            return Details(client.Id);
        }
    }
}

MvcManagerCloud/ManagerCloud.MVC/Views/Items/Create.cshtml
@model ManagerCloud.MVC.Models.Entities.Item

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New item</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    <div>
        @Html.LabelFor(model => model.Name, "Name")
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>

    <input type="submit" value="Create" />
    <p>@(ViewBag.Message != null ? ViewBag.Message : "")</p>
}

MvcManagerCloud/ManagerCloud.MVC/Views/Items/Delete.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model ManagerCloud.MVC.Models.Entities.Item
<h2>Remove item</h2>
<dl>
    <dt>Name</dt>
    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>

@using (Html.BeginForm())
{
    <input type="submit" value="Remove" />
}

MvcManagerCloud/ManagerCloud.MVC/Views/Items/Details.cshtml
@model ManagerCloud.MVC.Models.Entities.Item
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div class="modal-content">
    <div class="modal-header">
        <h4>Item</h4>
    </div>
    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>Name:</dt>
            <dd>@Html.DisplayFor(model => model.Name)</dd>
        </dl>
    </div>
</div>

MvcManagerCloud/ManagerCloud.MVC/Views/Items/Edit.cshtml
@{
    ViewBag.Title = "Edit item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model ManagerCloud.MVC.Models.Entities.Item

<h2>Item № @Model.Id</h2>
@using (Html.BeginForm("Edit", "Items", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <fieldset>
        @Html.HiddenFor(client => client.Id)

        @Html.LabelFor(client => client.Name, "Name")
        @Html.EditorFor(client => client.Name)
        @Html.ValidationMessageFor(client => client.Name)

        <p><input type="submit" value="Submit"/></p>
        <p>@(ViewBag.Message != null ? ViewBag.Message : "")</p>

    </fieldset>
}

MvcManagerCloud/ManagerCloud.MVC/Views/Items/Index.cshtml
@model IEnumerable<ManagerCloud.MVC.Models.Entities.Item>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div>
    <input type="text" name="name" data-autocomplete-source='@Url.Action("AutocompleteSearch", "Items")' />
    <input type="submit" value="Search" />
</div>

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

@Html.ActionLink("Create", "Create")

<table id="jqg"></table>
<div id="jpager"></div>

<script src="~/Scripts/jquery-3.3.1.min.js" type="text/javascript"></script>
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/jquery-ui-1.12.1.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.jqGrid.min.js" type="text/javascript"></script>
<link href="~/Content/themes/base/all.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/i18n/grid.locale-en.js" type="text/javascript"></script>

<style>
    .ui-jqgrid .ui-pg-input {
        height: 20px;
    }

    .ui-jqgrid .ui-jqgrid-pager {
        height: 50px;
    }
</style>

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            $("[data-autocomplete-source]").each(function () {
                var target = $(this);
                target.autocomplete({ source: target.attr("data-autocomplete-source") });
            });
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#jqg").jqGrid({
                url: '@Url.Action("GetData")',
                datatype: "json",
                colNames: ['Id', 'Name'],
                colModel: [
                    { name: 'Id', index: 'Id', width: 50, stype: 'text' },
                    { name: 'Name', index: 'Name', width: 250, sortable: true},
                ],
                rowNum: 10,
                rowList: [10, 20, 30],
                width: 800,
                pager: '#jpager',
                loadonce:true,
                sortname: 'Id',
                sortorder: "desc",
                caption: "List items"
            });
            $("#jqg").jqGrid('navGrid', '#jpager', {

                search: true,
                searchtext: "Search",
                refresh: true,
                add: false,
                del: false,
                edit: false,
                view: true,
                viewtext: "View",
                viewtitle: "Current row",
                addtext: "Add",
                edittext: "Edit",
                deltext: "Del"
                }
            );
        });
    </script>
}