MvcManagerCloud/ManagerCloud.MVC/Models/Entities/Client.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ManagerCloud.MVC.Models.Entities
{
    public class Client
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Required to fill")]
        [Display(Name = "First name")]
        [StringLength(30, ErrorMessage = "Too many chars")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Required to fill")]
        [Display(Name = "Last name")]
        [StringLength(40, MinimumLength = 2, ErrorMessage = "The length of the string must be from 2 to 40 characters")]
        public string LastName { get; set; }
    }
}

MvcManagerCloud/ManagerCloud.MVC/Controllers/ClientsController.cs
using ManagerCloud.BL;
using ManagerCloud.MVC.Models.Entities;
using ManagerCloud.MVC.ViewModels;
using System;
using System.ComponentModel;
using System.Web.Mvc;
using ManagerCloud.MVC.Filters;

namespace ManagerCloud.MVC.Controllers
{
    public class ClientsController : Controller
    {
        private const int MyFirstClientId = 260;
        private readonly Unity _unity = new Unity();

        // GET: Clients
        public ActionResult Index()
        {
            var customers = Helpers.BlModelConversion.GetListClients();

            var viewModel = new IndexClientViewModel
            {
                Clients = customers
            };

            return View(viewModel);
        }

        // GET: Clients
        [UserAuthentication]
        [OutputCache(Duration = 300)]
        public ActionResult Details([DefaultValue(MyFirstClientId)] int id)
        {
            var client = _unity.GetClient(id);
            if (client == null)
            {
                return HttpNotFound();
            }

            var customer = new Client
            {
                Id = client.Item1,
                FirstName = client.Item2,
                LastName = client.Item3
            };

            return View(customer);
        }

        [LocalAuthorize(Roles = "admin")]
        [HttpGet]
        [OutputCache(Duration = 300)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var client = _unity.GetClient((int)id);
            if (client == null)
            {
                return HttpNotFound();
            }

            var customer = new Client
            {
                Id = client.Item1,
                FirstName = client.Item2,
                LastName = client.Item3
            };

            return View(customer);
        }

        [LocalAuthorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(Client client)
        {
            if (ModelState.IsValid)
            {
                _unity.UpdateClient(new Tuple<int, string, string>(client.Id, client.FirstName, client.LastName));
            }
            else
            {
                ViewBag.Message = "Failed";
                return View();
            }

            ViewBag.Message = "Successful";
            return RedirectToAction("Index");
        }

        [LocalAuthorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [LocalAuthorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create([Bind(Include = "FirstName,LastName")] Client client)
        {
            if (ModelState.IsValid)
            {
                _unity.AddClient(new Tuple<string, string>(client.FirstName, client.LastName));
            }
            else
            {
                ViewBag.Message = "Failed";
                return View();
            }

            ViewBag.Message = "Successful";
            return RedirectToAction("Index");
        }

        [LocalAuthorize(Roles = "admin")]
        [OutputCache(Duration = 300)]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var client = _unity.GetClient((int)id);
            if (client == null)
            {
                return HttpNotFound();
            }

            var customer = new Client
            {
                Id = client.Item1,
                FirstName = client.Item2,
                LastName = client.Item3
            };

            return View(customer);
        }

        [LocalAuthorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var client = _unity.GetClient(id);
            if (client == null)
            {
                return HttpNotFound();
            }

            _unity.RemoveClient(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult ClientSearch(string fName, string lName)
        {
            var listClients = Helpers.BlModelConversion.GetListClients();
            if (!string.IsNullOrEmpty(fName))
            {
                listClients = listClients.FindAll(client => client.FirstName.Contains(fName));
            }
            if (!string.IsNullOrEmpty(lName))
            {
                listClients = listClients.FindAll(client => client.LastName.Contains(lName));
            }

            return PartialView(listClients);
        }
    }
}

MvcManagerCloud/ManagerCloud.MVC/Views/Clients/ClientSearch.cshtml
@model IEnumerable<ManagerCloud.MVC.Models.Entities.Client>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="searchresults">
    <h3>Find customer(s): </h3>
    <table id="table">
        <tr>
            <th>First name</th>
            <th>Last name</th>
            <th></th>
        </tr>
        @foreach (var customer in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(@customer.FirstName, "Details", new { id = customer.Id })
                </td>
                <td>
                    @Html.ActionLink(@customer.LastName, "Details", new { id = customer.Id })
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = customer.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = customer.Id })
                </td>
            </tr>
        }
    </table>
</div>

MvcManagerCloud/ManagerCloud.MVC/Views/Clients/Create.cshtml
@model ManagerCloud.MVC.Models.Entities.Client

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New client</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    <div class="clientBlock">
        @Html.LabelFor(model => model.FirstName, "First name")
        @Html.EditorFor(model => model.FirstName)
        @Html.ValidationMessageFor(model => model.FirstName)
        <br />
        @Html.LabelFor(model => model.LastName, "Last name")
        @Html.EditorFor(model => model.LastName)
        @Html.ValidationMessageFor(model => model.LastName)
    </div>

    <input type="submit" value="Create" />
    <p>@(ViewBag.Message != null ? ViewBag.Message : "")</p>
}

MvcManagerCloud/ManagerCloud.MVC/Views/Clients/Delete.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model ManagerCloud.MVC.Models.Entities.Client
<h2>Remove client</h2>
<dl>
    <dt>First name</dt>
    <dd>
        @Html.DisplayFor(model => model.FirstName)
    </dd>

    <dt>Last name</dt>
    <dd>
        @Html.DisplayFor(model => model.LastName)
    </dd>

</dl>

@using (Html.BeginForm())
{
    <input type="submit" value="Remove" />
}

MvcManagerCloud/ManagerCloud.MVC/Views/Clients/Details.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model ManagerCloud.MVC.Models.Entities.Client

<h2>Client № @Model.Id</h2>
<p>@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id })</p>
@Html.DisplayForModel()

MvcManagerCloud/ManagerCloud.MVC/Views/Clients/Edit.cshtml
@{
    ViewBag.Title = "Edit client";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model ManagerCloud.MVC.Models.Entities.Client
<h2>Client № @Model.Id</h2>
@using (Html.BeginForm("Edit", "Clients", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <fieldset>
        @Html.HiddenFor(client => client.Id)
        <p>
            @Html.LabelFor(client => client.FirstName, "First Name")
            <br />
            @Html.EditorFor(client => client.FirstName)
            @Html.ValidationMessageFor(client => client.FirstName)
        </p>
        <p>
            @Html.LabelFor(client => client.LastName, "Last Name")
            <br />
            @Html.EditorFor(client => client.LastName)
            @Html.ValidationMessageFor(client => client.LastName)

        </p>
        <p><input type="submit" value="Submit" /></p>
        <p>@(ViewBag.Message != null ? ViewBag.Message : "")</p>

    </fieldset>
}

MvcManagerCloud/ManagerCloud.MVC/Views/Clients/Index.cshtml
@model ManagerCloud.MVC.ViewModels.IndexClientViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="Client">Clients</h2>
<p>@Html.ActionLink("Create", "Create")</p>

@if (Model.Clients.Count == 0)
{
    <text>No customers.</text>
}
else
{
    <div>
        @using (Ajax.BeginForm("ClientSearch",
            new AjaxOptions
            {
                UpdateTargetId = "results",
                Confirm = "Do a search?",
                LoadingElementId = "loading"
            }))
        {
            <label>Last name</label>
            <input type="text" name="lName" />

            <label>Fisrt name</label>
            <input type="text" name="fName" />

            <input type="submit" value="Search" />
        }
        <div id="loading" style="display:none; color:Red; font-weight:bold;">
            <p>Loading...</p>
        </div>
        <div id="results"></div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")
}